---
zookeeper_connect = "localhost:2181"
broker_id = "1"
partitions = "1"
default_rf = "1"
retention = "1"
log_segment = "104857600"
auto_create_topics_enable = "false"
offsets_rf = "1"
heap = "1"
dataDir = "/var/lib/zookeeper/data"
zkid = "1"
kafka_dir = "/var/lib/kafka"
