---
- name: zoo_kafka_singleinstance
  become: yes
  tasks:

  - name: Create {{ dataDir }}
    file:
      path: "{{ dataDir }}"
      state: directory
      owner: kafka
      group: kafka
      mode: '0755'

  - name: Create {{ dataDir }}/myid symbolic link
    file:
      src: /etc/zookeeper/myid
      dest: {{ dataDir }}/myid
      state: link
    notify: Restart zookeeper

  - name: Create Zookeeper service file
    template: 
      src: templates/zookeeper.service.j2
      dest: /etc/systemd/system/zookeeper.service
      owner: root
      group: root
      mode: '0644'
    notify: Daemon reload

  - name: Create Kafka service file
    template:
      src: templates/kafka.service.j2
      dest: /etc/systemd/system/kafka.service
      owner: root
      group: root
      mode: '0644'
    notify: Daemon reload

  - name: Create Zookeeper config file
    template:
      src: templates/zookeeper.j2
      dest: /etc/zookeeper/zoo.cfg
      owner: kafka
      group: kafka
      mode: '0644'
    notify: Restart zookeeper

  - name: Create Kafka config file
    template:
      src: templates/kafka.j2
      dest: {{ kafka_dir }}/config/server.properties
      owner: kafka
      group: kafka
      mode: '0644'
    notify: Restart kafka

  - name: Jolokia-telegraf config
    template:
      src: templates/jolokia_telegraf.j2
      dest: /etc/telegraf/telegraf.d/input-jolokia.conf
      owner: telegraf
      group: telegraf
      mode: '0644'
    notify: Restart telegraf  

  - name: Add symlink to java executable
    file:
      src: /usr/bin/java
      dest: /usr/lib/jvm/jdk-11.0.10/bin/java
      state: link

  - name: Make sure the kafka service unit is enabled and running
    systemd:
      state: started
      name: kafka
      enabled: yes

  - name: Make sure the zookeeper service unit is enabled and running
    systemd:
      state: started
      name: zookeeper
      enabled: yes

  - name: Make sure the telegraf service unit is enabled and running
    systemd:
      state: started
      name: telegraf
      enabled: yes
    
handlers:
  - name: Restart telegraf
    systemd:
      name: telegraf
      state: restarted

  - name: Restart zookeeper
    systemd:
      name: zookeeper
      state: restarted

  - name: Restart kafka
    systemd:
      name: kafka
      state: restarted

  - name: Daemon reload
    systemd:
      daemon_reload: yes
